### PR TITLE
Mm 6.0 wcnss

### PR DESCRIPTION
**Pull request by alviteri**
@jerpelea 

[   11.638605] init: cannot find '/system/vendor/bin/wcnss_service', disabling 'wcnss_service'

### CODE REVIEW

**Comment by jerpelea** [comment]
This service is needed

**Comment by alviteri** [comment]
then the binary will be included ?

**Comment by jerpelea** [comment]
It is for devices that need it

**Comment by alviteri** [comment]
ok thank you

**Pull request closed without merging**
