### PR TITLE
yukon: LatinIME: enable input gesture

### PR DESCRIPTION
**Pull request by alviteri**
Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by galaxyfreak** [comment]
This is actually part of GApps, not sure if it should be enabled like this.

**Comment by alviteri** [comment]
@galaxyfreak part of gapps ??? You mean about google keyboard or what

**Comment by galaxyfreak** [comment]
Yes. But I'm not sure - didn't use gapps in ages.

**Comment by alviteri** [comment]
You mean libjni .so if yes OK but remember this project doesn't work with gapps .. This has own way (AOSP only) and if AOSP gives you the possibility of has input gestures why not compile it ... Anyway @jerpelea decides if merge or not

**Pull request merged**
