### PR TITLE
Fixes for the backlight and the internal SD card

### PR DESCRIPTION
**Pull request by gtrentalancia**
This pull request aims to fix the following two issues in the yukon platform:

- the backlight is kept always on (causing a massive battery drain);
- the internal SD card (internal storage) is not mounted correctly at system bootup.

### CODE REVIEW

**Comment by jerpelea** [comment]
push to the proper branch!

**Comment by gtrentalancia** [comment]
The master branch does not have the rootdir/init.yukon.rc file ! Which branch do you mean ?

**Comment by gtrentalancia** [comment]
The issue is hitting KitKat. I don't know about other Android versions, although it probably affects them too.

**Comment by gtrentalancia** [comment]
I have double-checked and the branch mentioned in the official Sony instructions is kk_mr2:

https://developer.sonymobile.com/open-devices/aosp-build-instructions/how-to-build-aosp-kitkat-for-unlocked-xperia-devices/

**Pull request closed without merging**
