### PR TITLE
init.yukon.rc: Use timekeep instead of time_daemon

### PR DESCRIPTION
**Pull request by galaxyfreak**
I didn't try this out yet, but it should be okay

### CODE REVIEW

**Comment by galaxyfreak** [comment]
Time is still messed up after factory reset

**Comment by erikcas** [comment]
@galaxyfreak really? I donot have them. I think this should be added?

**Comment by jerpelea** [comment]
with those packages added timekeep works nice 
this time i will fix it for you 
next time i will reject the commit

**Comment by galaxyfreak** [comment]
I did "make TimeKeep" manually to build them, but they were there for my test anyway. Whatever.

**Pull request merged**
