### PR TITLE
sepolicy: include initial sepolicy

### PR DESCRIPTION
**Pull request by AdFad666**
all good except the timekeep problems below.

### CODE REVIEW

**Comment by AdFad666** [comment]
<5>[    9.256625] type=1400 audit(60662.639:3): avc:  denied  { read write } for  pid=256 comm="rmt_storage" name="mmcblk0p19" dev="tmpfs" ino=8605 scontext=u:r:rmt_storage:s0 tcontext=u:object_r:block_device:s0 tclass=blk_file permissive=1

<38>[    9.473139] type=1400 audit(60662.659:4): avc: denied { open } for pid=256 comm="rmt_storage" path="/dev/block/mmcblk0p19" dev="tmpfs" ino=8605 scontext=u:r:rmt_storage:s0 tcontext=u:object_r:block_device:s0 tclass=blk_file permissive=1

<38>[   12.801175] type=1400 audit(60666.179:5): avc: denied { net_raw } for pid=333 comm="sct_service" capability=13 scontext=u:r:sct:s0 tcontext=u:r:sct:s0 tclass=capability permissive=1

<38>[   12.959565] type=1400 audit(60666.339:6): avc: denied { dac_override } for pid=336 comm="addrsetup" capability=1 scontext=u:r:addrsetup:s0 tcontext=u:r:addrsetup:s0 tclass=capability permissive=1

<38>[   12.959871] type=1400 audit(60666.339:7): avc: denied { write } for pid=336 comm="addrsetup" name="tad" dev="tmpfs" ino=6760 scontext=u:r:addrsetup:s0 tcontext=u:object_r:tad_socket:s0 tclass=sock_file permissive=1

<38>[   12.960251] type=1400 audit(60666.339:8): avc: denied { connectto } for pid=336 comm="addrsetup" path="/dev/socket/tad" scontext=u:r:addrsetup:s0 tcontext=u:r:tad:s0 tclass=unix_stream_socket permissive=1

<38>[   12.991508] type=1400 audit(60666.369:9): avc: denied { net_raw } for pid=329 comm="ta_qmi_service" capability=13 scontext=u:r:ta_qmi:s0 tcontext=u:r:ta_qmi:s0 tclass=capability permissive=1

<38>[   13.008807] type=1400 audit(60666.389:10): avc: denied { net_raw } for pid=335 comm="sensors.qcom" capability=13 scontext=u:r:sensors:s0 tcontext=u:r:sensors:s0 tclass=capability permissive=1

<38>[   13.136498] type=1400 audit(60666.519:11): avc: denied { write } for pid=336 comm="addrsetup" name="etc" dev="mmcblk0p25" ino=112225 scontext=u:r:addrsetup:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1

<38>[   13.136657] type=1400 audit(60666.519:12): avc: denied { add_name } for pid=336 comm="addrsetup" name="bluetooth_bdaddr" scontext=u:r:addrsetup:s0 tcontext=u:object_r:system_data_file:s0 tclass=dir permissive=1

<38>[   13.136812] type=1400 audit(60666.519:13): avc: denied { create } for pid=336 comm="addrsetup" name="bluetooth_bdaddr" scontext=u:r:addrsetup:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1

<38>[   13.136923] type=1400 audit(60666.519:14): avc: denied { write open } for pid=336 comm="addrsetup" path="/data/etc/bluetooth_bdaddr" dev="mmcblk0p25" ino=112226 scontext=u:r:addrsetup:s0 tcontext=u:object_r:system_data_file:s0 tclass=file permissive=1

<38>[   13.137029] type=1400 audit(60666.519:15): avc: denied { write } for pid=336 comm="addrsetup" name="wcnss_mac_addr" dev="sysfs" ino=11707 scontext=u:r:addrsetup:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=1

<38>[   40.275735] type=1400 audit(60693.659:16): avc: denied { write } for pid=2257 comm="m.sony.timekeep" name="property_service" dev="tmpfs" ino=7416 scontext=u:r:platform_app:s0 tcontext=u:object_r:property_socket:s0 tclass=sock_file permissive=1

<38>[   40.276535] type=1400 audit(60693.659:17): avc: denied { connectto } for pid=2257 comm="m.sony.timekeep" path="/dev/socket/property_service" scontext=u:r:platform_app:s0 tcontext=u:r:init:s0 tclass=unix_stream_socket permissive=1

<14>[   40.277020] avc:  denied  { set } for property=persist.sys.timeadjust scontext=u:r:platform_app:s0 tcontext=u:object_r:system_prop:s0 tclass=property_service

<38>[   43.522356] type=1400 audit(1434146636.114:18): avc: denied { connectto } for pid=2257 comm="m.sony.timekeep" path="/dev/socket/property_service" scontext=u:r:platform_app:s0 tcontext=u:r:init:s0 tclass=unix_stream_socket permissive=1

**Comment by jerpelea** [comment]
more testing needed

**Comment by AdFad666** [comment]
TimeKeep needs to be modified to be a proper system app. Testing now.

**Comment by AdFad666** [comment]
sepolicy is now ready for Yukon. No denials even after using various hardware features.

**Pull request merged**
